### ISSUE TITLE
mpd connection constantly times out

### ISSUE THREAD

**Issue by hoelzro** [hoelzro/obvious#2]
I fixed this by patching my own obvious code to use a larger timeout.  The default is one second; Arch Linux recently updated LuaSocket to version 3.0, though, so I get the feeling that it's interpreting this 1 as milliseconds rather than seconds.  If you use the mpd widget, please let me know if you see the behavior or not.

**Comment by hoelzro** [comment]
This turns out to be a bug with the LuaSocket package on Arch Linux:

https://github.com/diegonehab/luasocket/commit/396e9e5

This commit fixes the bug, and was made after the 3.0rc1 release.

**Comment by sergeyklay** [comment]
:+1:

**Comment by hoelzro** [comment]
Arch bug: https://bugs.archlinux.org/task/43361?string=socket&project=1&type[0]=&sev[0]=&pri[0]=&due[0]=&reported[0]=&cat[0]=&status[0]=open&percent[0]=&opened=&dev=&closed=&duedatefrom=&duedateto=&changedfrom=&changedto=&openedfrom=&openedto=&closedfrom=&closedto=
