### ISSUE TITLE
Battery widget not working on desktop computer

### ISSUE THREAD

**Issue by vonpupp** [hoelzro/obvious#22]
Hello,

Ok, I understand the title may not make much sense, however let me try to explain. I use my awesome config across my notebook and desktop. I have on both installed acpi but on my desktop I get an error as soon as I `require("obvious.battery")`. Herewith my desktop output:

    > $ acpi
    No support for device type: power_supply

Herewith the dump of the error:

    stack traceback:
    	/home/av/.config/awesome/obvious/battery/init.lua:49: in function </home/av/.config/awesome/obvious/battery/init.lua:48>
    error: /home/av/.config/awesome/obvious/battery/init.lua:49: attempt to index a nil value (upvalue 'backend')
    WARN: event_handle_error:186: X error: request=ChangeWindowAttributes (major=2, minor=0, resource=4e00001), error=BadWindow

Perhaps it is a special case it is not handled? Any advice?

Thank you very much.

**Comment by hoelzro** [comment]
@vonpupp Which commit of obvious are you using?  Have you tried a different battery reporting command, such as upower?

**Comment by hoelzro** [comment]
Closing pending further information.  If this is still a bug in the future, please feel free to re-open!
