### ISSUE TITLE
README for the battery widget is wrong

### ISSUE THREAD

**Issue by boris-petrov** [hoelzro/obvious#24]
It says that one could get information about the battery widget by calling `obvious.battery.get_data()`. However, there is no such function. I need it to test whether there is a battery at all as I use the same config for desktops and for laptops. What should I use instead?

**Comment by hoelzro** [comment]
@boris-petrov Unfortunately, there's nothing I expose in obvious itself to allow this (but it's something I'm interested in supporting).  Here's how I handle it: https://github.com/hoelzro/awesome-config/blob/master/widgets.lua#L21

**Comment by boris-petrov** [comment]
Thank you, this worked, although I had to put the `require 'obvious.battery'` inside the if-statement as otherwise I was periodically getting some error in `battery/init.lua`.

You can close this issue I guess, however the fact remains that the README IS wrong. :) Besides, what is written in the README worked before (in commit 352954b17e4ae7c4acdeab3756c4ef5949eb5e1d). :)

**Comment by hoelzro** [comment]
@boris-petrov I just added `get_data` and updated the README, please give it a try!  I also added some functionality so that the battery widget blinks red if the charge drops below 20%, so let me know if you see any strange behavior due to that.

**Comment by boris-petrov** [comment]
Thanks! However, on a desktop machine with no battery, the moment I require `obvious.battery`, I keep getting the following error every second:
`.../obvious/battery/init.lua:57: attempt to index a nil value (upvalue 'backend')`.
So the `get_data` function is not that useful as I have to anyway use `has_battery` from your solution above. As I said - the way it was in 352954b17e4ae7c4acdeab3756c4ef5949eb5e1d was best. :)

**Comment by hoelzro** [comment]
@boris-petrov Interesting; it shouldn't do that until you actually call `obvious.battery()`.  I'll take a look after work and see if I can get rid of that error.

**Comment by hoelzro** [comment]
@boris-petrov Which version of Awesome are you using?

**Comment by boris-petrov** [comment]
```
%  awesome --version
awesome v3.5.9 (Mighty Ravendark)
 • Build: Mar 12 2016 01:11:40 for x86_64 by gcc version 5.3.0 (builduser@rw)
 • Compiled against Lua 5.3.2 (running with Lua 5.3)
 • D-Bus support: ✔
```

I'm on Arch Linux.

**Comment by hoelzro** [comment]
Ok, I'm on the same version of Awesome and the same distro, so that makes this easier. =)

Would you mind sharing your awesome config?  I'm not sure why `require 'obvious.battery'` is setting up the battery update to run.

**Comment by boris-petrov** [comment]
Hi, sorry for the delayed answer, you can find my config here:

https://github.com/boris-petrov/dotfiles/blob/master/Linux/.config/awesome/rc.lua

If you add `require("obvious.battery")` somewhere at the beginning and change lines 193 and 194 to `if obvious.battery.get_data() then`, the issue will appear.

**Comment by hoelzro** [comment]
Thanks!  I see what's going on here; you're calling `obvious.battery.get_data()`, which uses the backend object to get data from the battery.  However, the backend is only set up (and thus non-nil) if you've called `obvious.battery()`, which you *don't* want to do if you don't have a battery, so we have a so-called "chicken and egg" problem.  I'll fix this up later today.

**Comment by hoelzro** [comment]
@boris-petrov Ok; I just made a change for this.  Please try out the latest obvious and let me know of your findings.

**Comment by boris-petrov** [comment]
It seems to work fine both on my desktop and on my laptop. :) Thanks for that! Now the README is correct and I can close the issue. Thanks for your time!
