### ISSUE TITLE
Error when no battery present

### ISSUE THREAD

**Issue by p-himik** [hoelzro/obvious#25]
It appears that null_backend doesn't work as expected - its state() method returns an empty battery with subsequent error in update().

**Comment by p-himik** [comment]
Looks like returning nil from null_backend:state() does fix it.

**Comment by hoelzro** [comment]
@p-himik Thanks for the report; I'll fix this up.

**Comment by hoelzro** [comment]
@p-himik I just applied your suggested fix; it should be working now!

**Comment by p-himik** [comment]
Works, thanks!
