### ISSUE TITLE
Error when using acpitool battery backend

### ISSUE THREAD

**Issue by p-himik** [hoelzro/obvious#26]
Just installed acpitool for my battery-less laptop hibernation issue, and suddenly Awesome WM stopped working.
Apparently if no battery is present, both acpi and acpitool backends should not only check for `exists`, but also that they return correct `Battery #...` line (e.g. on my machine with no battery acpitool returns ` Battery status : <not available>`). Otherwise, Awesome spits out `attempt to index local 'data' (a nil value)`.

**Comment by hoelzro** [comment]
@p-himik Thanks for the report!  Which OS/distribution are you using?

**Comment by p-himik** [comment]
Oh, right. Ubuntu 16.04, acpitool 0.5.1-4.

**Comment by hoelzro** [comment]
Thanks! I'll spin up an Ubuntu VM and work on a fix.  I have limited Internet access at the moment, though, so it may take me a few days.

**Comment by hoelzro** [comment]
@p-himik I just made a change that should fix this - please give it a shot!~

**Comment by p-himik** [comment]
It doesn't break the whole WM anymore, but I think the change should be made more conforming to the upower backend. Right now the acpi backend can be correctly configured even when there is no battery - this leads to this backend being selected, even though the null backend would be a better choice. Because of this, the widget shows `unknown nil%`.

**Comment by p-himik** [comment]
I'll create a pull request in a bit.
