### ISSUE TITLE
Awesome 4.0 support

### ISSUE THREAD

**Issue by p-himik** [hoelzro/obvious#29]
Do you have any plans on Awesome 4.0 support?

**Comment by hoelzro** [comment]
@p-himik I haven't made the switch to Awesome 4 yet, so until I do, I probably won't work on making it happen.  I will, however, accept patches that add Awesome 4 support as long as they don't break 3.5 =)

**Comment by p-himik** [comment]
Ok, thanks. I guess I'll give it a try some time soon.
