### ISSUE TITLE
Awesome 4 weather widget

### ISSUE THREAD

**Issue by vonpupp** [hoelzro/obvious#33]
Hello,

I am trying the `weather` and it seem to have an issue. The error is: forecast.lua:1: module 'socket' not found.

I am using Lua 5.3.3 on Arch Linux.

**Comment by hoelzro** [comment]
@vonpupp You'll need to install `lua-socket` for that module to work.

**Comment by vonpupp** [comment]
Thank you @hoelzro, I don't know almost nothing about Lua.
