### ISSUE TITLE
Update to lua 5.3

### ISSUE THREAD

**Issue by francois2metz** [hoelzro/obvious#36]
Hi, 

Debian is now building awesome with lua 5.3. It basically break the use of `module`. See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=880143 and http://lua-users.org/wiki/ModulesTutorial.

Would you accept some pull request to fix this?

## Status

- [ ] cpu
- [ ] fs_usage
- [ ] io
- [ ] mem
- [ ] wlan
- [ ] basic_mpd
- [x] battery #37 
- [ ] clock
- [x] temp_info #37 
- [ ] keymap_switch

**Comment by hoelzro** [comment]
I've been using Lua 5.3 with obvious for a while now on Arch - I'm guessing it's built with `LUA_COMPAT_MODULE` on Arch, though.  I would be happy to accept PRs that fix things for Debian!

**Comment by hoelzro** [comment]
This should be fixed now!
